spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/amp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aBcd!234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        type: trace
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
 